### ISSUE TITLE
Metal and Mac

### ISSUE THREAD

**Issue by pablovela5620** [google/slang-gaussian-rasterization#1]
Hi, Thank you for the great release! I'm wondering if this would make it possible to train splats on Mac GPUs. I saw the mention of a bunch of different platforms like D3D, Vulkan, OpenGL, OptiX, CUDA etc. So is it reasonable to assume I could make this work on an M1 Mac?

**Comment by brabbitdousha** [comment]
Based on my development experience with slangpy, it currently only supports Python bindings for CUDA

**Comment by pablovela5620** [comment]
Great thanks for the response

**Comment by saipraveenb25** [comment]
Some additional context: The slang _compiler_ (more info: https://github.com/shader-slang/slang) supports several backends. The `.slang` kernels (and the code generated from auto-diff) can be compiled to CUDA, HLSL (for D3D), SPIR-V, GLSL, MetalSL, C & WGSL (in-progress).
However, the `slangtorch` wrapper library used in this framework only provides a CUDA run-time since its quick & easy to set up using PyTorch as a dependency. 
If you already have a rendering framework that uses D3D/Vulkan/Metal, the slang shader files can be reused with that.
